MERGE usr.Orders AS target
USING (
    SELECT DISTINCT 
        ord_id,
        ord_parentOrderId,
        ord_orderTypeCode,
        ord_reference,
        ord_invoiceReference,
        ord_orderStatusName,
        ord_allocationStatusCode,
        ord_stockStatusCode,
        ord_shippingStatusCode,
        ord_orderPaymentStatus,
        ord_channelId,
        chn_name,
        con_billingAddressLine3,
        con_billingcountryId,
        con_billingCountryIsoCode,
        con_billingAddressLine4,
        con_billingPostalCode,
        con_defaultaddressLine3,
        con_defaultcountryId,
        con_defaultcountryIsoCode,
        con_defaultaddressLine4,
        con_defaultPostalCode,
        ord_createdById,
        ord_staffOwnerContactId,
        ord_orderCurrencyCode,
        ord_placedOn,
        ord_createdOn,
        ord_invoicetaxDate,
        ord_invoicedueDate,
        ord_deliveryDate,
        ord_exchangeRate,
        ord_fixedExchangeRate,
        ord_net,
        orl_itemCostValue,
        ord_total,
        orl_rowTaxValue,
        orl_quantity,
        CASE WHEN ord_historicalOrder = 0 THEN 'No' ELSE 'Yes' END AS HistoricalOrder,
        CASE WHEN ord_isDropship = 0 THEN 'No' ELSE 'Yes' END AS IsDropship,
        ord_leadSourceId,
        lsc_name,
        cmp_paymentMethodCode,
        cmp_paymentType,
        ord_costPriceListId,
        ord_priceListId,
        ord_shippingMethodId,
        shm_name,
        ord_warehouseId,
        ocf_id,
        omd_code,
        omd_name,
        omd_customFieldType,
        ocf_value,
        CASE WHEN con_isSupplier = 1 THEN con_defaultaddressLine3 ELSE NULL END AS SupplierCity,
        CASE WHEN con_isSupplier = 1 THEN con_organisationName ELSE NULL END AS SupplierCompany,
        CASE WHEN con_isSupplier = 1 THEN con_id ELSE NULL END AS SupplierContactId,
        CASE WHEN con_isSupplier = 1 THEN con_defaultcountryIsoCode ELSE NULL END AS SupplierCountryCode,
        CASE WHEN con_isSupplier = 1 THEN con_defaultcountryId ELSE NULL END AS SupplierCountryId,
        CASE WHEN con_isSupplier = 1 THEN con_defaultaddressLine4 ELSE NULL END AS SupplierState,
        CASE WHEN con_isSupplier = 1 THEN con_defaultPostalCode ELSE NULL END AS SupplierZip,
        CASE WHEN con_isSupplier = 1 THEN con_emailsPRI ELSE NULL END AS SupplierEmail,
        CASE WHEN con_isSupplier = 1 THEN CONCAT(con_firstName, ' ', con_lastName) ELSE NULL END AS SupplierName
    FROM 
        dbo.tblOrder
    LEFT JOIN dbo.tblOrderLine ON ord_id = orl_ord_id
    LEFT JOIN dbo.tblJournalTransaction ON ord_id = jtr_orderId 
    LEFT JOIN dbo.tblJournal ON jtr_jou_id = jou_id
    LEFT JOIN dbo.tblContact ON ord_createdById = con_id
    LEFT JOIN dbo.tblLeadSource ON ord_leadSourceId = lsc_id
    LEFT JOIN dbo.tblCustomerPayment ON ord_id = cmp_orderId
    LEFT JOIN dbo.tblShippingMethod ON ord_shippingMethodId = shm_id
    LEFT JOIN dbo.tblOrderCustomField ON ord_id = ocf_ord_id
    LEFT JOIN dbo.tblOrderCustomFieldMetadata ON ocf_id = omd_id
    LEFT JOIN dbo.tblChannel ON ord_channelId = chn_id
) AS source
ON target.[Order Id] = source.ord_id
WHEN NOT MATCHED BY TARGET THEN
    INSERT (
        [Order Id],
        [Parent Order Row Id],
        [Type],
        [Reference Number],
        [Invoice Reference],
        [Status],
        [Allocation Status],
        [Inventory Status],
        [Shipping Status],
        [Payment Status],
        [Channel ID],
        [Channel Name],
        [Billing City],
        [Billing Country Id],
        [Billing Country Code],
        [Billing State],
        [Billing Zip],
        [Delivery City],
        [Delivery Country Id],
        [Delivery Country Code],
        [Delivery State],
        [Delivery Zip],
        [Created By ID],
        [Employee ID],
        [Currency],
        [Order Date],
        [Created At Date],
        [Tax Date],
        [Original Invoice Date],
        [Delivery Date],
        [Exchange Rate],
        [Fixed Exchange Rate],
        [Net Value],
        [Cost],
        [Revenue],
        [Tax Amount],
        [Quantity],
        [Historical Order (Yes / No)],
        [Is Dropship (Yes/No)],
        [Lead Source ID],
        [Lead Source Name],
        [Payment Method Code],
        [Payment Method],
        [Cost Price ID],
        [Price List],
        [Shipping Method ID],
        [Shipping Method],
        [Warehouse ID],
        [Custom Field ID],
        [Custom Field Code],
        [Custom Field Name],
        [Custom Field Type],
        [Custom Field Value],
        [Supplier City],
        [Supplier Company],
        [Supplier Contact Id],
        [Supplier Country Code],
        [Supplier Country Id],
        [Supplier State],
        [Supplier Zip],
        [Supplier Email],
        [Supplier Name]
    )
    VALUES (
        source.ord_id,
        source.ord_parentOrderId,
        source.ord_orderTypeCode,
        source.ord_reference,
        source.ord_invoiceReference,
        source.ord_orderStatusName,
        source.ord_allocationStatusCode,
        source.ord_stockStatusCode,
        source.ord_shippingStatusCode,
        source.ord_orderPaymentStatus,
        source.ord_channelId,
        source.chn_name,
        source.con_billingAddressLine3,
        source.con_billingcountryId,
        source.con_billingCountryIsoCode,
        source.con_billingAddressLine4,
        source.con_billingPostalCode,
        source.con_defaultaddressLine3,
        source.con_defaultcountryId,
        source.con_defaultcountryIsoCode,
        source.con_defaultaddressLine4,
        source.con_defaultPostalCode,
        source.ord_createdById,
        source.ord_staffOwnerContactId,
        source.ord_orderCurrencyCode,
        source.ord_placedOn,
        source.ord_createdOn,
        source.ord_invoicetaxDate,
        source.ord_invoicedueDate,
        source.ord_deliveryDate,
        source.ord_exchangeRate,
        source.ord_fixedExchangeRate,
        source.ord_net,
        source.orl_itemCostValue,
        source.ord_total,
        source.orl_rowTaxValue,
        source.orl_quantity,
        source.HistoricalOrder,
        source.IsDropship,
        source.ord_leadSourceId,
        source.lsc_name,
        source.cmp_paymentMethodCode,
        source.cmp_paymentType,
        source.ord_costPriceListId,
        source.ord_priceListId,
        source.ord_shippingMethodId,
        source.shm_name,
        source.ord_warehouseId,
        source.ocf_id,
        source.omd_code,
        source.omd_name,
        source.omd_customFieldType,
        source.ocf_value,
        source.SupplierCity,
        source.SupplierCompany,
        source.SupplierContactId,
        source.SupplierCountryCode,
        source.SupplierCountryId,
        source.SupplierState,
        source.SupplierZip,
        source.SupplierEmail,
        source.SupplierName
    )
WHEN MATCHED THEN
    UPDATE SET
        target.[Parent Order Row Id] = source.ord_parentOrderId,
        target.[Type] = source.ord_orderTypeCode,
        target.[Reference Number] = source.ord_reference,
        target.[Invoice Reference] = source.ord_invoiceReference,
        target.[Status] = source.ord_orderStatusName,
        target.[Allocation Status] = source.ord_allocationStatusCode,
        target.[Inventory Status] = source.ord_stockStatusCode,
        target.[Shipping Status] = source.ord_shippingStatusCode,
        target.[Payment Status] = source.ord_orderPaymentStatus,
        target.[Channel ID] = source.ord_channelId,
        target.[Channel Name] = source.chn_name,
        target.[Billing City] = source.con_billingAddressLine3,
        target.[Billing Country Id] = source.con_billingcountryId,
        target.[Billing Country Code] = source.con_billingCountryIsoCode,
        target.[Billing State] = source.con_billingAddressLine4,
        target.[Billing Zip] = source.con_billingPostalCode,
        target.[Delivery City] = source.con_defaultaddressLine3,
        target.[Delivery Country Id] = source.con_defaultcountryId,
        target.[Delivery Country Code] = source.con_defaultcountryIsoCode,
        target.[Delivery State] = source.con_defaultaddressLine4,
        target.[Delivery Zip] = source.con_defaultPostalCode,
        target.[Created By ID] = source.ord_createdById,
        target.[Employee ID] = source.ord_staffOwnerContactId,
        target.[Currency] = source.ord_orderCurrencyCode,
        target.[Order Date] = source.ord_placedOn,
        target.[Created At Date] = source.ord_createdOn,
        target.[Tax Date] = source.ord_invoicetaxDate,
        target.[Original Invoice Date] = source.ord_invoicedueDate,
        target.[Delivery Date] = source.ord_deliveryDate,
        target.[Exchange Rate] = source.ord_exchangeRate,
        target.[Fixed Exchange Rate] = source.ord_fixedExchangeRate,
        target.[Net Value] = source.ord_net,
        target.[Cost] = source.orl_itemCostValue,
        target.[Revenue] = source.ord_total,
        target.[Tax Amount] = source.orl_rowTaxValue,
        target.[Quantity] = source.orl_quantity,
        target.[Historical Order (Yes / No)] = source.HistoricalOrder,
        target.[Is Dropship (Yes/No)] = source.IsDropship,
        target.[Lead Source ID] = source.ord_leadSourceId,
        target.[Lead Source Name] = source.lsc_name,
        target.[Payment Method Code] = source.cmp_paymentMethodCode,
        target.[Payment Method] = source.cmp_paymentType,
        target.[Cost Price ID] = source.ord_costPriceListId,
        target.[Price List] = source.ord_priceListId,
        target.[Shipping Method ID] = source.ord_shippingMethodId,
        target.[Shipping Method] = source.shm_name,
        target.[Warehouse ID] = source.ord_warehouseId,
        target.[Custom Field ID] = source.ocf_id,
        target.[Custom Field Code] = source.omd_code,
        target.[Custom Field Name] = source.omd_name,
        target.[Custom Field Type] = source.omd_customFieldType,
        target.[Custom Field Value] = source.ocf_value,
        target.[Supplier City] = source.SupplierCity,
        target.[Supplier Company] = source.SupplierCompany,
        target.[Supplier Contact Id] = source.SupplierContactId,
        target.[Supplier Country Code] = source.SupplierCountryCode,
        target.[Supplier Country Id] = source.SupplierCountryId,
        target.[Supplier State] = source.SupplierState,
        target.[Supplier Zip] = source.SupplierZip,
        target.[Supplier Email] = source.SupplierEmail,
        target.[Supplier Name] = source.SupplierName;