SELECT TOP (1000) [orl_id]
      ,[orl_gen]
      ,[orl_ord_id]
      ,[orl_orderRowSequence]
      ,[orl_productId]
      ,[orl_productName]
      ,[orl_productSku]
      ,[orl_quantity]
      ,[orl_itemCostCurrencyCode]
      ,[orl_itemCostValue]
      ,[orl_taxRate]
      ,[orl_taxCode]
      ,[orl_taxCalculator]
      ,[orl_rowNetCurrencyCode]
      ,[orl_rowNetValue]
      ,[orl_rowTaxCurrencyCode]
      ,[orl_rowTaxValue]
      ,[orl_nominalCode]
      ,[orl_compositionBundleParent]
      ,[orl_compositionBundleChild]
      ,[orl_parentOrderRowId]
      ,[orl_productPriceCurrencyCode]
      ,[orl_productPriceValue]
      ,[orl_discountPercentage]
      ,[orl_taxClassId]
      ,[orl_clonedFromId]
  FROM [dbo].[tblOrderLine]
  WHERE [orl_ord_id] = 1865330 